Updated poco::dynamic::var to std::any in core.
moja-global/FLINT pull request #67
Opened 2020-08-30 11:20 UTC by parth-gr

Check and edit these files ones for some common issues of DynamicObject:-
proxymodule.cpp
outputstream.cpp
Writesystemconfig.h
Writevariablegrid.cpp
Writesystemconfig.cpp
localdomaincontrollerbase.cpp
writevariablegrid.cpp
lookuprandomtransform.cpp
lookuptransform.cpp
sumpoolstransform.cpp
compositetransform.cpp

2020-08-30 11:36 UTC, parth-gr commented
Signed-off-by: parth-gr 50455445+parth-gr@users.noreply.github.com

2020-08-31 02:18 UTC, malfrancis requested changes
This pull request has pulled in several commits from previous check-ins these should be removed with just the latest changes. I'm not sure how this happened. 
Poco::Dynamic should be replaced and there should be no need for Poco::JSON

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/include/moja/flint/proxymodule.h
> +#include <Poco/JSON/Parser.h>
Should not be needed

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/include/moja/flint/proxymodule.h
> +                            std::shared_ptr<IModule> module, const Poco::Dynamic::Var& config);
Should be DynamicObject

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/include/moja/flint/proxymodule.h
> +                            std::shared_ptr<IModule> module, const Poco::Dynamic::Var& config, std::string variableName,
should be DynamicObject

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/src/outputerstream.cpp
> +#include <Poco/JSON/Parser.h>
should not be needed

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/src/outputerstream.cpp
> +#include "Poco/Dynamic/Struct.h"
should not be needed

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/src/outputerstream.cpp
> +void outputDynamicToStream(std::ostream& fout, const Poco::Dynamic::Var& object) {
should be DynamicVar

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/src/proxymodule.cpp
> +#include <Poco/JSON/Parser.h>
should not be needed

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/src/proxymodule.cpp
> +                                 std::shared_ptr<IModule> module, const Poco::Dynamic::Var& config) {
should be DynamicObject

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/src/proxymodule.cpp
> +void ProxyModule::configure(const Poco::Dynamic::Var& config) {
should be DynamicObject

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/src/variableandpoolstringbuilder.cpp
> +#include <Poco/JSON/Parser.h>
should not be needed

2020-08-31 02:18 UTC, malfrancis commented on Source/moja.flint/src/variableandpoolstringbuilder.cpp
> +void outputDynamicToStream_XX(std::ostream& fout, const Poco::Dynamic::Var& object) {
shoud be DynamicVar

2020-08-31 04:44 UTC, parth-gr commented
> This pull request has pulled in several commits from previous check-ins these should be removed with just the latest changes. I'm not sure how this happened.
> Poco::Dynamic should be replaced and there should be no need for Poco::JSON

Okay, sir, I will update the pull request and I will update the Poco::Dynamic.

2020-08-31 07:15 UTC, parth-gr commented on Source/moja.flint/src/variableandpoolstringbuilder.cpp
> +void outputDynamicToStream_XX(std::ostream& fout, const Poco::Dynamic::Var& object) {
Done

2020-08-31 08:00 UTC, parth-gr commented
Sir please the updation I have done.
I am not getting the pervious commits how they are coming, sir, you may please look on this repo: https://github.com/parth-gr/FLINT/commits/feature/profile I have given the access to you.

I tried git-rebase, still figuring if I can remove those commits.

2020-08-31 11:57 UTC, parth-gr commented
@malfrancis Sir in this PR, Like I was able to remove the last commits, but it's like giving an overhead of again and again commits, so should I provide a new PR?

2020-09-01 12:17 UTC, closed without merging